configs/reports/configs/tl-reports.yml

updated tl reports config files.

update tl reports config 

---

configs/egov-persister/tradelicense-persister.yml

updated tradelicense persister for UAT

updated tradelicense persister for UAT

---

configs/egov-persister/egov-workflow-v2-persister.yml
configs/egov-persister/tradelicense-persister.yml

persister updated for workflow

persister updated for workflow 

---

configs/reports/configs/pt-reports.yml

Added column Pending Amount

---

configs/reports/configs/pt-reports.yml

new column added as receipt no

new column added as receipt no

---

configs/reports/configs/pt-reports.yml

new column removed

---

configs/reports/configs/ptreport.yml

new pt file created with 3 columns

new pt file created with 3 columns

---

configs/reports/report.config

new file configured

---

configs/reports/configs/pt-reports.yml

only some columns which are not needed are trimmed off, or heading of some columns has been changed and will be updated through localization

PT receipt register short report created

---

configs/reports/configs/uc-reports.yml

New Report added Misc

---

configs/reports/report.config

Reverts egovernments/punjab-rainmaker-customization#197

Revert "Update report.config"

---

configs/egov-persister/tradelicense-persister.yml

Add additionalDetail in query with jsonPath PI-6854

Add additionalDetail in query with jsonPath PI-6854

---

configs/reports/configs/tl-reports.yml

excluded testing tenant from TL StateLevelStatusReport

exuded testing tenant frm TL StateLevelStatusReport

---

configs/reports/configs/pgr-reports.yml

[PI-7032] Feedback Report for PGR in State Reports

[PI-7032] Feedback Report for PGR in State Reports

---

configs/reports/configs/pgr-reports.yml

Update Feedback Report

---

configs/reports/configs/pgr-reports.yml

update state report

---

configs/reports/configs/pgr-reports.yml

Update feedback report on UAT

---

configs/reports/configs/pgr-reports.yml

PI-7032 state wise Feedback report

PI-7032 state wise  Feedback report

---

configs/reports/report.config

create new report for HRMS module PI-7425

create new report for HRMS module PI-7425

---

configs/reports/configs/tl-reports.yml

Fixed Reports were not able to filter between dates

tl-report-fix-for-QA

---

configs/reports/configs/pgr-reports.yml

Update Description Report

---

configs/reports/configs/pgr-reports.yml

Update PGR Description Report in PROD

Update PGR Description Report in PROD

---

configs/reports/configs/pgr-reports.yml

Update missing column in PGR Description Report

Update missing column in PGR Description Report

---

configs/reports/configs/pgr-reports.yml

Update ActionTakenDate in Description Report in PGR

Update ActionTakenDate in Description Report in PGR

---

configs/reports/configs/pt-reports.yml
configs/reports/configs/tl-reports.yml

ULB Level Status report was including FireNoc Applications status also, thi problem may have been introduced after rolling out of firenoc module as firenoc applications also have same status

fixed ULBLevelStatusReport

---

configs/egov-indexer/rainmaker-pt-indexer.yml

changing property index type to general

[PI-866] making property index type is general

---

configs/reports/configs/pgr-reports.yml

pgr correction assigned to query

pgr correction assigned to query

---

configs/egov-indexer/property-services-migration-temp.yml

Created file property-services-migration-temp.yml to do indexing while doing the migration

Created file property-services-migration-temp.yml

---

configs/reports/configs/tl-reports.yml

PI-8952,  updated trade license Reports
Adding new Pendency Report

PI-8952 Update tl-reports.yml

---

configs/reports/configs/tl-reports.yml

assignee label in TL pendency report

---

configs/reports/configs/pt-reports.yml

 PI-8971 Adding PendingPTApplicationsReport

---

configs/reports/configs/tl-reports.yml

change in TL pendency report for assignee column

changes in assignee

---

configs/reports/configs/pt-reports.yml

Report name change PendingPTApplicationsReport for mapping with action test

Report name change PendingPTApplicationsReport

---

configs/reports/configs/ws-reports.yml

new report in Water sewerage BaseRegisterReportWS

new report in Water sewerage BaseRegisterReportWS

---

configs/reports/configs/ws-reports.yml

FieldCollectionSearchReceiptWS &  FieldCollectionSearchReportWS

Adding two WS Reports

---

configs/reports/configs/ws-reports.yml

Adding new report Search Online Receipts WS in water sewerage

Adding new report Search Online Receipts WS

---

configs/reports/configs/tl-reports.yml

Adding no. of days pending from

Changes in TL Pendency Report

---

configs/reports/configs/tl-reports.yml

Adding new column in Pendency report

Adding new column in TL Pendency report

---

configs/reports/configs/tl-reports.yml

update TL report with ward and zone

update TL report with ward and zone

---

configs/reports/configs/ws-reports.yml

UPDATING WS REPORTS WITH TYPE FILED STRING

UPDATING WS REPORTS

---

configs/reports/configs/ws-reports.yml

Adding Receipt Collections Report in WS

Adding Receipt Collections Report in WS

---

configs/reports/configs/tl-reports.yml

report correction of TL

---

configs/reports/configs/uc-reports.yml

UC Employee Collection Report

---

configs/reports/configs/tl-reports.yml

Employee Wise Collection Report TL

Employee Wise Collection Report TL

---

configs/reports/configs/uc-reports.yml

tenant id issue correction in UC Report

tenant id issue correction in UC Report

---

configs/reports/configs/tl-reports.yml

tenant id correction in TL collection report

tenant id correction in TL collection report

---

migration_wns_java/migrationkit/src/main/java/org/egov/migrationkit/service/ConnectionService.java
migration_wns_java/migrationkit/src/main/java/org/egov/migrationkit/service/RecordService.java

Wns migration migrating duplicate records

---

configs/egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

 [PI-9847] - Changes on uat Dashboard

---

configs/egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

[PI-9847]-changing chart type from line to bar in PT dashboard

---

configs/egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

changed the date reference filed to issuedDate for tlStatusByDDR

changed the date reference filed to issuedDate for tlStatusByDDR

---

configs/egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

added aggregation path and pathdata mapping for status by boundary

Updated status by boundary in TL

---

configs/egov-dss-dashboards/dashboard-analytics/MasterDashboardConfig.json

UM-5403 - UM-5403 - Punjab Add mCollect & Fire NoC in Punjab mSeva DSS Dashboard

UM-5403 - UM-5403 - Punjab Add mCollect & Fire NoC in Punjab mSeva DSS Dashboard

---

configs/egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

UM-5403 removed round off

---

configs/egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json

UM-5403 Removed FSM and BPA from aggrQuery

UM-5403 Removed FSM and BPA from aggrQuery
